version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"